name: build-and-test-for-pull-request

on:
  pull_request:

jobs:
  back-end-for-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build and test back end
        run: docker compose -f docker-compose.ci.back-end.yml up --build --exit-code-from back-end

  web-app-for-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build and test web app
        run: docker compose -f docker-compose.ci.web-app.yml up --build --exit-code-from web-app
