name: Deploy main on staging

on:
  workflow_run:
    workflows: ["fix-formatting-and-build-and-test-for-push-on-main-and-dev"]
    branches: [main]
    types:
      - completed

jobs:
  deploy-main-on-staging:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Call webhook to deploy main branch on staging environment
        run: curl ${{ secrets.URL_WEBHOOK_DEPLOY_MAIN_ON_STAGING }}
